# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cb6d0bd8b4d9c6abb356e165c7ff76c7ed73c1c44114e0a0e8c35ed5f0affc62b152f1875262214fddf691ea1706efff5913860a3c08beb9e21d06a50497da0

test:
  secret_key_base: fd8305770b2c0046f8b8bcc6024945ca5bb4c43e43164ca551cb1238c2e17a533b51c478094fd32ca1b9ab78e3d6d150ed912579d42ab821474c2e372c9fd943

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
